services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whatsapp-backend
    env_file:
      - .env
    command: npm run dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whatsapp-worker
    env_file:
      - .env
    command: npm run dev:worker
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whatsapp-frontend
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:7
    container_name: whatsapp-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: whatsapp-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mongo_data:
  redis_data:

networks:
  app-network:
    driver: bridge
